import { readdirSync } from 'node:fs'
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// The /analysis/<slug>/ entries are GENERATED by scripts/build-pages.mjs
// (in prebuild) and committed, so they are on disk before this config runs.
//
// Globbed rather than imported: this file is what defines the `@/` alias, so it
// cannot use it to read the content module that owns the slugs. The generator
// is the single source; this just follows what it wrote.
const analysisEntries = () => {
  const dir = fileURLToPath(new URL('./analysis', import.meta.url))
  const entries = {}

  for (const slug of readdirSync(dir, { withFileTypes: true })) {
    if (slug.isDirectory()) {
      entries[`analysis-${slug.name}`] = fileURLToPath(
        new URL(`./analysis/${slug.name}/index.html`, import.meta.url)
      )
    }
  }

  return entries
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  base: '/',
  publicDir: 'public',
  resolve: {
    alias: {
      // New-site imports use "@/..." and always resolve inside src/.
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    assetsDir: 'assets',
    copyPublicDir: true,
    rollupOptions: {
      // Multi-page build: "/", the analysis index, one entry per analysis
      // detail page, and the tutorial.
      input: {
        main: fileURLToPath(new URL('./index.html', import.meta.url)),
        // Explicit: analysisEntries() only walks DIRECTORIES, so the index page
        // sitting as a file directly in analysis/ is skipped by the glob. That
        // is why it is listed here rather than being picked up automatically.
        analysis_index: fileURLToPath(new URL('./analysis/index.html', import.meta.url)),
        // Also explicit: the glob walks analysis/ only, and nothing generalises
        // it, so a new top-level page is one line here.
        tutorial: fileURLToPath(new URL('./tutorial/index.html', import.meta.url)),
        ...analysisEntries(),
      },
      output: {
        assetFileNames: 'assets/[name][extname]'
      }
    }
  }
})
