// Generates the HTML entry for every subpage: /analysis/, the four
// /analysis/<slug>/ pages, and /tutorial/.
//
// Why generated: a Vite MPA entry needs a real HTML file on disk, and with no
// HTML templating plugin each one carries its own ~150-line <head>. Six pages
// written by hand would be ~900 lines with ~570 of them byte-identical copies,
// including the anti-FOUC theme script that must stay in step with
// src/lib/theme.js. One template, six writes, one place to change.
//
// Runs in `prebuild`, and the output is COMMITTED — same deal as
// src/lib/releaseImageWidths.js. Committing is what lets `npm run dev` serve
// these pages without anyone running the build first, and it is also why
// vite.config.js can simply glob the directory.
//
// It reads the content module through Vite's SSR loader because that module
// imports via the `@/` alias, which bare Node cannot resolve.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://code-xr.adrianmonteslinares.com';

// Lifted verbatim from index.html rather than re-typed. If the two ever differ,
// a page flashes the wrong theme on load — so it is read, not copied.
const themeScript = async () => {
  const html = await readFile(join(root, 'index.html'), 'utf8');
  // \r?\n throughout: the repo checks out with CRLF on Windows.
  const match = html.match(/ {4}<script>\r?\n[\s\S]*?\r?\n {4}<\/script>/);

  if (!match) {
    throw new Error('build-analysis-pages: could not find the theme script in index.html.');
  }

  return match[0];
};

const template = ({ page, theme }) => `<!doctype html>
<html lang="en">
  <head>
    <!--
      GENERATED by scripts/build-analysis-pages.mjs — do not edit by hand.
      The copy comes from src/content/analysisPagesContent.js.
    -->
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="%BASE_URL%favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${page.seoTitle}</title>
    <meta name="description" content="${page.seoDescription}" />
    <meta name="author" content="Adrian Montes Linares" />
    <meta name="application-name" content="Code-XR" />
    <meta name="robots" content="index, follow" />
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#fafbfc" />
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#0e141b" />
${theme}
    <link rel="canonical" href="${ORIGIN}${page.path}" />

    <meta property="og:type" content="article" />
    <meta property="og:site_name" content="Code-XR" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:title" content="${page.seoTitle}" />
    <meta property="og:description" content="${page.seoDescription}" />
    <meta property="og:url" content="${ORIGIN}${page.path}" />
    <meta property="og:image" content="${ORIGIN}/social-preview.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="Code-XR title card: the Code-XR mark and wordmark over the tagline &quot;Code analysis you can walk through&quot;." />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${page.seoTitle}" />
    <meta name="twitter:description" content="${page.seoDescription}" />
    <meta name="twitter:image" content="${ORIGIN}/social-preview.png" />
    <meta name="twitter:image:alt" content="Code-XR title card: the Code-XR mark and wordmark over the tagline &quot;Code analysis you can walk through&quot;." />

    <!--
      A STUB. scripts/prerender.mjs replaces this whole block on every subpage
      with the real @graph (the page's own type, its BreadcrumbList, the author
      node and, where there is one, a VideoObject). It lives here only so the
      page is valid before postbuild runs and so the dev server serves something
      coherent; the prerender asserts the replacement, so the stub cannot reach
      production unnoticed.
    -->
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "${page.ldType}",
        "headline": ${JSON.stringify(page.seoTitle)},
        "description": ${JSON.stringify(page.seoDescription)},
        "url": "${ORIGIN}${page.path}",
        "inLanguage": "en",
        "about": { "@type": "SoftwareApplication", "name": "Code-XR" }
      }
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${page.entryScript}"></script>
  </body>
</html>
`;

const run = async () => {
  const vite = await createServer({
    root,
    logLevel: 'error',
    server: { middlewareMode: true },
    appType: 'custom',
  });

  try {
    const { analysisPages } = await vite.ssrLoadModule('/src/content/analysisPagesContent.js');
    const { tutorial } = await vite.ssrLoadModule('/src/content/tutorialContent.js');
    const theme = await themeScript();

    // `path`, `entryScript` and `ldType` are what differ between families, so
    // they are fields rather than assumptions baked into the template. `path`
    // rather than a slug, so pages that have no slug (the index, the tutorial)
    // use the same template as the four that do.
    //
    // The analysis pages are TechArticle: reference material about one feature.
    // The tutorial is HowTo, and prerender.mjs replaces this stub with the full
    // block including its steps and its VideoObject — the same split the home's
    // FAQPage uses, so the copy has one home in the content module.
    const ANALYSIS_ENTRY = '/src/app/analysisMain.jsx';

    const entries = [
      {
        dir: join(root, 'analysis'),
        page: {
          ...analysisPages.index,
          path: '/analysis/',
          entryScript: ANALYSIS_ENTRY,
          ldType: 'TechArticle',
        },
      },
      ...analysisPages.pages.map((page) => ({
        dir: join(root, 'analysis', page.slug),
        page: {
          ...page,
          path: `/analysis/${page.slug}/`,
          entryScript: ANALYSIS_ENTRY,
          ldType: 'TechArticle',
        },
      })),
      {
        dir: join(root, 'tutorial'),
        page: {
          ...tutorial,
          path: '/tutorial/',
          entryScript: '/src/app/tutorialMain.jsx',
          ldType: 'HowTo',
        },
      },
    ];

    for (const entry of entries) {
      await mkdir(entry.dir, { recursive: true });
      await writeFile(join(entry.dir, 'index.html'), template({ page: entry.page, theme }), 'utf8');
    }

    console.log(
      `[pages] wrote ${entries.length} entries: ` +
        entries.map((entry) => entry.page.path).join(', ')
    );
  } finally {
    await vite.close();
  }
};

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
